<?php


$estadoLocal = [
    "ACTIVO",
    "INACTIVO",
];

$listaTipoAveria = [
    "RADIO",
    "ENERGIA",
    "TRANSPORTE",
];

$listaEstado = [
    "PENDIENTE",
    "CERRADO",
    "ANULADO",
    "RECHAZADO",

];

$listaZonales = [
    "LIMA",
    "AREQUIPA",
    "CUSCO",
    "PUNO",
    "TACNA",

];

$listaMotivoPR =[
    "",
    "CORTE DE ENERGÍA COMERCIAL CON/SIN INSTALACIÓN DE GE",
    "FENOMENOS NATURALES",
    "FUERA DE HORA PARA SUBIR A TORRE",
    "OBRA COMPLEMENTARIA",
    "REPUESTOS ENERGIA POR IMPORTACIÓN",
    "REPUESTOS ENERGIA POR OBSOLESCENCIA",
    "REPUESTOS RADIO",
    "REPUESTOS TRANSMISIONES",
    "SIN ACCESO POR HUELGA / BLOQUEO / ZONA PELIGROSA",
    "SIN ACCESO POR INDISPONIBILIDAD DE LLAVES",
    "SIN ACCESO POR INSTITUCIÓN PÚBLICA O PRIVADA",
    "SIN ACCESO POR PROCEDIMIENTOS DE SEGURIDAD TDP/TORRERA/OPERADOR (SITIO COUBICADO)",
    "SIN ACCESO POR PROPIETARIO NO UBICABLE Y/O DISPONIBLE",
    "SOPORTE TDP",
    "SOPORTE TERCEROS",
    "TRASLADO EXTREMO DE ENLACE",
];

$listaTipoCierre =[
    "",
    "ABASTECIMIENTO COMBUSTIBLE",
    "CAMBIO DE EQUIPO / REPARACION / REPUESTO / CONSUMIBLE",
    "CESE AUTOMATICO",
    "CORTE DE ENERGIA Y CESE AUTOMATICO",
    "DESCARTE, NO CORRESPONDE",
    "FALSA ALARMA",
    "INSTALACION DE GE O BATERIAS",
    "REVISION / RESET / AJUSTES / LIMPIEZA"
];


?>